//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.DevExpress_Web_ASPxGridView_V17 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxGridView_V17._1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Zwiń].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_DragAndDropHideColumnIcon {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_DragAndDropHideColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Rozwiń].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Warunek].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_FilterRowButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_FilterRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Filtr].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Filtrowany].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButtonActive {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Rosnąco).
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Malejąco).
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaczyna się od.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterBeginsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawiera.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterContains {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zawiera.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterDoesNotContain {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kończy się na.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEndsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równy.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEquals {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jest większy niż.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreater {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jest większy lub równy.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreaterOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jest mniejszy niż.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLess {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jest mniejszy lub równy.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLessOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like (&apos;%&apos;, &apos;_&apos;).
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLike {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwa symbole wieloznaczne są obsługiwane:
        /// &apos;%&apos; zastępuje zero lub więcej znaków;
        /// &apos;_&apos; zastępuje jeden znak..
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLikeToolTip {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLikeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie jest równy.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterNotEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięte wartości.
        /// </summary>
        internal static string ASPxGridViewStringId_BatchEdit_ChangesPreviewDeletedValues {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.BatchEdit_ChangesPreviewDeletedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wstawione wartości.
        /// </summary>
        internal static string ASPxGridViewStringId_BatchEdit_ChangesPreviewInsertedValues {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.BatchEdit_ChangesPreviewInsertedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaktualizowane wartości.
        /// </summary>
        internal static string ASPxGridViewStringId_BatchEdit_ChangesPreviewUpdatedValues {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.BatchEdit_ChangesPreviewUpdatedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostosowanie.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_CommandCustomizationButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_CommandCustomizationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostosowanie.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż więcej kart....
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_EndlessPagingShowMoreCardsButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_EndlessPagingShowMoreCardsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ciąg dalszy).
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_GroupRow_Continued {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_GroupRow_Continued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_GroupSelector_ClearGroupingItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_GroupSelector_ClearGroupingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wierszy na stronie:.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_PagerRowPerPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_PagerRowPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopka karty.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_Toolbar_ShowCardFooter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_Toolbar_ShowCardFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagłówek panelu.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_Toolbar_ShowHeaderPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_Toolbar_ShowHeaderPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastosuj.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandApplyFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandApplySearchPanelFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandApplySearchPanelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj zmiany.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditCancel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj podgląd.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditHidePreview {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditHidePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd zmian.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditPreviewChanges {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditPreviewChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz zmiany.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditUpdate {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podsumowania aktualizacji.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditUpdateSummaries {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditUpdateSummaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandCancel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandClearFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandClearSearchPanelFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandClearSearchPanelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastosuj.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandCustomizationDialogApply {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandCustomizationDialogApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandCustomizationDialogClose {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandCustomizationDialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skasuj.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zaznaczenie wszystkich wierszy na wszystkich stronach.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandDeselectAllOnAllPages {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandDeselectAllOnAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zaznaczenie wszystkich wierszy na tej stronie.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandDeselectAllOnPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandDeselectAllOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandEdit {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandHideAdaptiveDetail {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandHideAdaptiveDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandNew {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odzyskać.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandRecover {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandSelect {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz wszystkie wiersze na wszystkich stronach.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandSelectAllOnAllPages {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandSelectAllOnAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz wszystkie wiersze na tej stronie.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandSelectAllOnPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandSelectAllOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string ASPxGridViewStringId_CommandShowAdaptiveDetail {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandShowAdaptiveDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandUpdate {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź kasowanie?.
        /// </summary>
        internal static string ASPxGridViewStringId_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz wykonać akcję? Wszystkie siatki niezapisane dane zostaną utracone..
        /// </summary>
        internal static string ASPxGridViewStringId_ConfirmOnLosingBatchChanges {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ConfirmOnLosingBatchChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść filtr.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ClearFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść grupowanie.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ClearGrouping {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ClearGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść sortowanie.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ClearSorting {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiń szczegóły.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_CollapseDetailRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_CollapseDetailRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiń.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_CollapseRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_CollapseRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_CopyToClipboard {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_DeleteRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_EditRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_EditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozwiń szczegóły.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ExpandDetailRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ExpandDetailRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozwiń.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ExpandRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ExpandRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksport.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_Export {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiń wszystko.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_FullCollapse {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_FullCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozwiń wszystko.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_FullExpand {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_FullExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupuj według tej kolumny.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_GroupByColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_GroupByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krótki opis grupy.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_GroupSummaryMenu {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_GroupSummaryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj kolumnę.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_HideColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_HideColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_NewRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_NewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wklej.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_PasteFromClipboard {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_PasteFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odśwież.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_Refresh {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż kolumny.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór kolumn.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowCustomizationWindow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowCustomizationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreator filtrów....
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowFilterEditor {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowFilterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr wiersza.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowFilterRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowFilterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu filtra wiersza.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowFilterRowMenu {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowFilterRowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopka.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowFooter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel grupowania.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowGroupPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowGroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel wyszukiwania.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowSearchPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortuj rosnąco.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SortAscending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortuj malejąco.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SortDescending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryAverage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licznik.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryCount {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimum.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryMax {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryMin {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryNone {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummarySum {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummarySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdziel.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_UngroupColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_UngroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór kolumn.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_ColumnChooserTab {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_ColumnChooserTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrowanie.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_FilterTab {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_FilterTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupowanie.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_GroupTab {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_GroupTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortowanie.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_SortTab {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_SortTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole wyboru.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak danych do wyświetlenia.
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyDataRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upuść kolumnę tutaj....
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyHeaders {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Kontynuacja na następnej stronie).
        /// </summary>
        internal static string ASPxGridViewStringId_GroupContinuedOnNextPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupContinuedOnNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upuść nagłówek kolumny tutaj by pogrupować po tej kolumnie.
        /// </summary>
        internal static string ASPxGridViewStringId_GroupPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterCancelButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterFrom {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W zeszłym miesiącu.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterLastMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W zeszłym tygodniu.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterLastWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatni rok.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterLastYear {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następny miesiąc.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterNextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W przyszłym tygodniu.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterNextWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W przyszłym roku.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterNextYear {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterNextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterOkButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Wybierz wszystko).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterSelectAll {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Wszystko).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowAllItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Puste).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowBlanksItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Nie puste).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowNonBlanksItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowNonBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W tym miesiącu.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W tym tygodniu.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterThisWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W tym roku.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterThisYear {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterTo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziś.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterToday {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jutro.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterTomorrow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczoraj.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterYesterday {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poza następnego miesiąca.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_BeyondNextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_BeyondNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wcześniej w tym miesiącu.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_EarlierThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_EarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W zeszłym miesiącu.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LastMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W zeszłym tygodniu.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LastWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Później w tym miesiącu.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LaterThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LaterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następny miesiąc.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_NextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następny tydzień.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_NextWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starsze.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Older {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za trzy tygodnie.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_ThreeWeeksAgo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_ThreeWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trzy tygodnie temu.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_ThreeWeeksAway {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_ThreeWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziś.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Today {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jutro.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Tomorrow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwa tygodnie później.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_TwoWeeksAgo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_TwoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwa tygodnie później.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_TwoWeeksAway {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_TwoWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczoraj.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Yesterday {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja formularza.
        /// </summary>
        internal static string ASPxGridViewStringId_PopupEditFormCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.PopupEditFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadzanie tekstu do wyszukiwania....
        /// </summary>
        internal static string ASPxGridViewStringId_SearchPanelEditorNullText {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.SearchPanelEditorNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan zaznaczenia wszystkich wierszy na wszystkich stronach.
        /// </summary>
        internal static string ASPxGridViewStringId_SelectAllCheckBoxInAllPagesMode {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.SelectAllCheckBoxInAllPagesMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan zaznaczenia wszystkich wierszy na tej stronie.
        /// </summary>
        internal static string ASPxGridViewStringId_SelectAllCheckBoxInPageMode {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.SelectAllCheckBoxInPageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia = {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Average {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG {1} jest {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Average_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Average_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba = {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Count {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimum={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Max {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimum {1} z {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Max_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Max_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min = {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Min {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min {1} jest {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Min_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Min_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Sum {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma z {1} wynosi {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Sum_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Sum_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Cancel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń filtr.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ClearFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść sortowanie.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ClearSorting {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiń.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_CollapseRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_CollapseRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Delete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Edit {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozwiń.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ExpandRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ExpandRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_New {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odśwież.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Refresh {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór kolumn.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowCustomizationWindow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowCustomizationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr wiersza.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowFilterRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowFilterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopka.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowFooter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel wyszukiwania.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowSearchPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel podsumowania.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowSummaryPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowSummaryPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizacja.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Update {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiń kategorię.
        /// </summary>
        internal static string ASPxGridViewStringId_VerticalGrid_AltCollapseCategory {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.VerticalGrid_AltCollapseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozwiń kategorię.
        /// </summary>
        internal static string ASPxGridViewStringId_VerticalGrid_AltExpandCategory {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.VerticalGrid_AltExpandCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozwiń wiersz.
        /// </summary>
        internal static string ASPxGridViewStringId_VerticalGrid_AltExpandRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.VerticalGrid_AltExpandRow", resourceCulture);
            }
        }
    }
}
